name: dyslexiadetectorapp
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  table_calendar: ^3.0.9
  intl: ^0.18.0
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/sounds/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Inika
      fonts: 
        - asset: assets/fonts/Inika.ttf
          weight: 400
