name: dyslexiadetectorapp
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.0.6 <=3.2.2'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  table_calendar: ^3.0.9
  intl: ^0.18.0
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
  flutter_tts: ^3.8.5
  percent_indicator: ^4.0.1
  english_words: ^4.0.0
  linear_timer: ^2.0.0
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_database: ^10.3.6
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  path: ^1.8.3
  provider: ^6.1.1

dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/logo.png
    - assets/images/login.png
    - assets/images/logo_navy.png
    - assets/images/role_wallpaper.png
    - assets/images/start_exam.png
    - assets/images/boy_avatar.png
    - assets/images/girl_avatar.png
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
    - family: OpenSansItalic
      fonts:
        - asset: assets/fonts/OpenSans-Italic-VariableFont.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont.ttf
    - family: SF
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: Inika
      fonts: 
        - asset: assets/fonts/Inika.ttf
          weight: 400
